### PR TITLE
Google Photos API

### PR DESCRIPTION
**Pull request by aniemoeller**
Hi!
I took some time to learn about flask / web stuff and python and moved the code to the google photos api. 
Unfortunately the api does not support keyword search at the moment so I edited your idea to find Albums / Shared albums by name or fall back to all images. Also the amount of pictures used can be set as well as image processing to fill the frame.
Let me know what you think.

### CODE REVIEW

**Comment by mrworf** [comment]
It's a great start, however it won't work as an upgrade since it will break people's frames (since me and many others rely on the keyword feature to show people and locations).

My intention was to abstract the access to content allowing users to run multiple service providers or multiple instances of the same one (his and hers 😸 ) and it will allow extending photoframe more easily in the future.

Would you be interested in porting this over to that design? I have a local branch for this but could push it so you can see.

**Comment by aniemoeller** [comment]
True ! About the keyword / people / location feature I saw that it is simply not implemented in the new Photos API but there is an open feature request for it. As of now the workaround would be to create an "intelligent" album using photos and to show that particular album. Afaik google will shut down the picasa api by end of january anyways.
Yes I assume the googlephotos.py was intended to be such service provider ?
Yes I'd definitely be interested in contributing.

**Comment by mrworf** [comment]
I got the impression that Google photos API already had it? See https://developers.google.com/photos/library/reference/rest/v1/mediaItems/search#ContentFilter

**Comment by aniemoeller** [comment]
Unfortunately only the categories given below ContentCategory but not arbitrary keywords.

**Comment by mrworf** [comment]
I see. I guess I hadn't thought of that. My plan was to keep picasa around and add the new one and have a more descriptive way of specifying, such as `person:"Henric Andersson" selfie` or `album:"Roadtrip 2010"` which allows for more finegrained keywording. Using HTML it wouldn't be hard to do a "build my search graphically" thing. This way everyone can remain on picasa (until dropped) and the newer method is there to allow migration. Could even do `album:"Roadtrip 2010" not selfie not landscape`. 

Most people using keywords only already do this, but using this method it would not randomly match the word `landscape` to both landscapes and the text landscape in a picture 😄

**Comment by mrworf** [comment]
Except I see now that you cannot specify location nor people. wtf

**Comment by aniemoeller** [comment]
Ya I think the only way around currently is with intelligent albums where you can add specific people or locations etc

**Comment by mrworf** [comment]
So it turns out when I revisited the branch that I hadn't really thought it out. I spent last night rethinking how this would work so it supports multiple services (and instances of the same) AND multiple keywords per service.

You'll find documents and initial version of the BaseService.py class. Have a look at SERVICE.md and see if it makes sense. The goal is that a new service should require minimal work, with most logic being in the base class and in photoframe itself.

Branch is called serviceapi

**Comment by aniemoeller** [comment]
Sounds good ! I'll have a look

**Pull request closed without merging**
